feat: 🎸 add layer dependency analysis javascript file
✅ Closes: PAR-2226

diff --git a/.github/actions/static-analysis/action.yml b/.github/actions/static-analysis/action.yml
--- a/.github/actions/static-analysis/action.yml
+++ b/.github/actions/static-analysis/action.yml
@@ -12,7 +12,10 @@ runs:
   steps:
     - name: Checkout Code
       uses: actions/checkout@v4
+      continue-on-error: true
+
     - name: Scan workflow yml files
+      id: scan-workflows
       run: |
         echo "Running the following script: ${{ github.action_path }}/scan_github_actions.js"
         echo "With the current working directory: $(pwd)"
@@ -21,3 +24,21 @@ runs:
       working-directory: ${{ github.workspace }}
       env:
         IGNORED_ACCOUNTS: ${{ inputs.ignored-accounts }}
+      continue-on-error: true
+
+    - name: Run layer dependency analysis
+      id: layer-dependency-analysis
+      run: |
+        echo "Running layer dependency analysis script"
+        node ${{ github.action_path }}/layer_dependency_analysis.js
+      shell: bash
+      working-directory: ${{ github.workspace }}
+      continue-on-error: true
+
+    - name: Check results
+      run: |
+        if [ "${{ steps.scan-workflows.outcome }}" != "success" ] || [ "${{ steps.layer-dependency-analysis.outcome }}" != "success" ]; then
+          echo "One or more steps failed"
+          exit 1
+        fi
+      shell: bash
